[package]
name = "v2pn"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "v2pn - secure proxy client (VLESS / REALITY / Hysteria2 / etc.)"
build = "build.rs"

[[bin]]
name = "v2pn"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
app-core = { path = "../app-core" }

reqwest.workspace = true

tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-deep-link = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-notification = "2"
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender = "0.2"
directories.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
